### ISSUE TITLE
RocketPool support

### ISSUE THREAD

**Issue by yorickdowne** [serenita-org/ethstaker.tax#13]
How feasible would it be to add automatic detection of RocketPool minipools and calculate consensus layer rewards that go to the node operator?

A column that has the node fee percentage, and a column that has the rewards earned by the NO, as opposed to earned by the validator: 

- 16 ETH minipool: Total rewards * 0.5 + total rewards * 0.5 * node fee percentage
- 8 ETH minipool: Total rewards * 0.25 + total rewards * 0.75 * node fee percentage

Acknowledged that this is easy enough to add manually to the generated CSV :)

**Comment by eth2353** [comment]
Very feasible and it's on my to-do list, see [the Gitcoin grant](https://gitcoin.co/grants/2148/eth2tax-tax-information-for-stakers).

I have decided to prioritize execution layer rewards over Rocketpool support (since that will benefit everyone, not just RPL node operators). I've been working on it in my free time since October but there are still some inconsistencies in the rewards calculation (especially when the fee recipient is a smart contract things can get interesting).

When I get to adding Rocketpool support I would like to include RPL rewards as well besides consensus layer rewards.

Do you know how to get the operator commission rate? I haven't looked into it yet, but I assume I'll need to go through events emitted by one of the Rocketpool contracts.

**Comment by aliask** [comment]
The commission rate for a Rocketpool validator can be found on chain or via the Beaconcha.in API.
For onchain, you can get this by looking at the deployment of the minipool contract (validator withdrawal address), which includes `_minimumNodeFee` corresponding to the commission rate of that validator.

The Beaconcha.in API also has an endpoint which contains a lot of relevant info, including the commission rate: `https://beaconcha.in/api/v1/rocketpool/validator/{index}`

You've possibly already figured this out, but I thought I'd drop the info here anyway.

**Comment by aliask** [comment]
Yeah, I agree that it would absolutely be best to have an independent implementation. But it's definitely more work 😅. 

I didn't realise that you had specific plans for Rocketpool. I actually submitted a [bounty application](https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/11?u=aliask) to the RP Grants Management Committee for a tax calculation tool a couple of week ago, and they will decide whether or not to include it in the next 5ish days. So there may be some incentive to complete the work!

One thing which I think is missing is the EL MEV rewards for those not in the smoothing pool. I'm pretty sure those get paid to the minipool delegate address, and then split according to the minipool commission. 

The commission only changes at very specific times (almost never). It's only when a minipool performs a "bond reduction", they go from their previous fee, to 14% (in the case of 8ETH minipools). So the commission should whatever they deployed the minipool at, or if they went through a bond reduction, 14%.

RPL and smoothing pool rewards are very complicated to calculate, but fortunately you don't have to do that. The oDAO members generate this data once per rewards period and publish the per-node data [on IPFS](https://gateway.ipfs.io/ipfs/bafybeiagazxkhdlyjqpba2hox4xhtf4jo5x5j4c3alc3kipfrt2g7seage/) and a reference to it (the CID) is [published on-chain](https://etherscan.io/tx/0x113d153cccdc76bf623090c11a65c40dcffd9e4f3d88b2d7d15c417c03ca2f30) when the rewards are distributed.

Rocketpool support is definitely not a small task, but it would help many people 🙏

**Comment by eth2353** [comment]
I found [this very helpful documentation](https://github.com/rocket-pool/rocketpool-research/blob/master/Merkle%20Rewards%20System/rewards-calculation-spec.md) of how the calculations are performed (and were performed historically).

**Comment by eth2353** [comment]
I've put _a lot_ of effort into this and it looks like I'm finally close to something viable.

A development version is running at http://194.163.155.173/preview , if anyone is subscribed to this issue and wants to give it a try, compare it to what they expect they earned, it would be greatly appreciated! Feel free to reach out to me in private as well, I'm on the Rocket Pool Discord among many more.

There are some limitations, but I believe it should work just fine for 99% of RP node operators:
- the transition from solo staker to a promoted minipool is not supported at the moment. If running promoted minipools, the workaround is to use the default mode for the date range where the validator was running "solo", and Rocket Pool mode for the date range after the promotion
- pre-Redstone RPL (September 2022) rewards are not supported
- due to the way the calculations work, the calculate request in Rocket Pool mode may take several minutes to return, especially if the node operator is not using the Smoothing Pool. At the extremes, e.g. with a node that has 450 linked minipools without SP, the request takes about 20 minutes currently.
- slashing scenarios are not handled right now but the request should return with an error response in this case, and not return incorrect/incomplete data

**Comment by eth2353** [comment]
Rocket Pool Mode is now a part of ethstaker.tax 🚀 enjoy!

Accompanying blog post: https://serenita.io/blog/ethstaker-tax-rocket-pool-mode
