### ISSUE TITLE
Maximum Call Stack Exceeded

### ISSUE THREAD

**Issue by kbdick** [serenita-org/ethstaker.tax#48]
Uncaught RangeError: Maximum call stack size exceeded. Seems to be an issue with custom dates.

![image](https://github.com/serenita-org/ethstaker.tax/assets/2249935/2fc8c865-933a-4c76-84be-7e9d6ac4a8a4)

**Comment by eth2353** [comment]
Hey, sorry about that, the Ethereum node that powers ethstaker.tax went offline temporarily due to an unexpected power outage. It is back online now, everything should be working again.

I tried using the inputs from your screenshot just now and it loads correctly for me now so I trust the issue is resolved. Let me know if I'm mistaken of course!

**Comment by kbdick** [comment]
No worries - wasn't clear from the 500 error. Not sure if it's possible to add a message to your error handling to show that the node is unreachable. It's working now - thanks for putting this together.
