### ISSUE TITLE
validator with index 426155 fails on slot 7194279

### ISSUE THREAD

**Issue by winksaville** [serenita-org/ethstaker.tax#60]
When I try to to 426155 with Date range of 08/26/2023 -> 08/28/2023 I get

"Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 426155, slot 7194279".

Other dates (01/01/2023 -> 08/26/2023 & 08/28/2023 -> 12/31/2023) there is no issue.

Seems to me you can use an "average" of earnings for that validator over a several day period on either side of missing data or just use "0". Of course it should be "reported" in some "logs" provided to the customer.

**Comment by pacts-bravos** [comment]
Also:

"Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 895817, slot 8478553"

"Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 917070, slot 8404441"

**Comment by eth2353** [comment]
> When I try to to 426155 with Date range of 08/26/2023 -> 08/28/2023 I get
> 
> "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 426155, slot 7194279".
> 
> Other dates (01/01/2023 -> 08/26/2023 & 08/28/2023 -> 12/31/2023) there is no issue.
> 
> Seems to me you can use an "average" of earnings for that validator over a several day period on either side of missing data or just use "0". Of course it should be "reported" in some "logs" provided to the customer.

The block in slot 7194279 contains a transaction from an MEV bot smart contract. On top of that, no MEV relay currently says it delivered the payload for that slot, resulting in ethstaker.tax being unable to index the rewards for that slot. This issue has been fixed, future blocks using the MEV bot smart contract will be indexed correctly. Here is the transaction in case you're interested:

https://etherscan.io/tx/0x3a2abb8256b3e3656f9330078504b5323e42e33ce4771d9f48c482cebd835b2d

> Also:
> 
> "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 895817, slot 8478553"
> 
> "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 917070, slot 8404441"

Similar issue here with a different smart contract, transactions:

https://etherscan.io/tx/0x36b29cb709a7aa6cb02aa356babf83726dfda83c307c0a530a816833e8fa8074
https://etherscan.io/tx/0x37af6cea1598528e111ef50b164cec193032ba5fc29493168bd5e1ed2adc9a0f

The slots you reported have been reindexed and should not result in error messages anymore!

To give you an idea of how frequently issues like this occur, out of  the 3.8M post-Merge blocks, we currently have 2.7k block reward data indexing failures. We prefer to give an error message in rare cases like these instead of reporting incomplete or inaccurate data.

I'll close this issue but don't hesitate to reach out again if there's anything else!

**Comment by winksaville** [comment]
> > When I try to to 426155 with Date range of 08/26/2023 -> 08/28/2023 I get
> > "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 426155, slot 7194279".
> > Other dates (01/01/2023 -> 08/26/2023 & 08/28/2023 -> 12/31/2023) there is no issue.
> > Seems to me you can use an "average" of earnings for that validator over a several day period on either side of missing data or just use "0". Of course it should be "reported" in some "logs" provided to the customer.
> 
> The block in slot 7194279 contains a transaction from an MEV bot smart contract. On top of that, no MEV relay currently says it delivered the payload for that slot, resulting in ethstaker.tax being unable to index the rewards for that slot. This issue has been fixed, future blocks using the MEV bot smart contract will be indexed correctly. Here is the transaction in case you're interested:
> 
> https://etherscan.io/tx/0x3a2abb8256b3e3656f9330078504b5323e42e33ce4771d9f48c482cebd835b2d
> 
> > Also:
> > "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 895817, slot 8478553"
> > "Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 917070, slot 8404441"
> 
> Similar issue here with a different smart contract, transactions:
> 
> https://etherscan.io/tx/0x36b29cb709a7aa6cb02aa356babf83726dfda83c307c0a530a816833e8fa8074 https://etherscan.io/tx/0x37af6cea1598528e111ef50b164cec193032ba5fc29493168bd5e1ed2adc9a0f
> 
> The slots you reported have been reindexed and should not result in error messages anymore!
> 
> To give you an idea of how frequently issues like this occur, out of the 3.8M post-Merge blocks, we currently have 2.7k block reward data indexing failures. We prefer to give an error message in rare cases like these instead of reporting incomplete or inaccurate data.
> 
> I'll close this issue but don't hesitate to reach out again if there's anything else!

TYVM, I've verified it is working for me!
