### ISSUE TITLE
missing data for proposer

### ISSUE THREAD

**Issue by pacts-bravos** [serenita-org/ethstaker.tax#75]
Hello,

Site gives me this error message.

"Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer 895818, slot 9168176"

**Comment by eth2353** [comment]
The reason for it is this transaction:

https://etherscan.io/tx/0x1336d11535dbe0f8db39cdad9b09b385a7ff247c39de7030e318b83e39e809b9

during which some ETH was transferred to your fee recipient address as part of a block your validator proposed. Not sure what to make of that transfer, is it some form of MEV you extracted yourself in a locally built block?

It's a very small amount of ETH but this is what made the indexer fail to process the rewards for the block.

**Comment by pacts-bravos** [comment]
Thank you for looking into this. I understand the problem. It’s a non-MEV validator and that transaction is either some kind of spam attack or some outside MEV operator accidentally sending to that address. My gut feeling is that it should be left out as it is not income based on my validators work?

**Comment by eth2353** [comment]
Thanks for providing some context, good to know this was not proposed through a relay / external builder.

Interestingly the tx's sender address seems to create lots of these transactions where a small amount of ETH is transferred to the block's fee recipient address - https://etherscan.io/txs?a=0x7847f222e2f7bde8d8f143b961df89f61e1e158d .

The only similar thing I can think of are 1 wei spam transactions which I've been discarding on the side of the indexer since it's such a negligible amount.

However, in this case it is much more than 1 wei, it is actually a few cents worth at today's prices so I'm not sure if it should just be ignored here... The sender address has also sent more than a few cents to block builders this way, e.g. https://etherscan.io/tx/0xbeb75bbd9ec5c8658a9f4eaf5fc7c7b6832828170c244e6b785775426ea1125b . Looks like the more CYG tokens are involved in the tx, the more the fee recipient address receives?

While it is not specifically payment for including txs in a block, it is payment to the current block's fee recipient and I feel like it should count as income - the small additional amount of ETH does end up under your control just like MEV.

**Comment by pacts-bravos** [comment]
Good point. I guess it depends on the tax regulation as well. If somebody spammed my address (fee or otherwise) random significant sum that would be income but not validating income. On the other hand if it happens always during block proposals I guess it’s easy to show that it is validating related. I think your suggestion of including this income to tax report is good and better than my first suggestion.

Thank you once again!

**Comment by eth2353** [comment]
I can't say with 100% certainty without seeing the code of the smart contract that was involved here, but I strongly believe you would not have gotten that reward if you were not specifically that block's proposer, therefore I would lean towards validator income, albeit indirect and admittedly a bit weird.

I have manually fixed the entry for this block in the ethstaker.tax database so you should be able to pull data for your validator again without any errors!
